name: ci-golang-workflow
on: [push]
jobs:
  check-apllication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        white:
          go-version: 1.15
      - run: go test
      - run: go run math.go